### ISSUE TITLE
Run time error with Ember4.1.0 and ember-auto-import@2.3.0

### ISSUE THREAD

**Issue by xomaczar** [josemarluedke/glimmer-apollo#55]
Uncaught Error: Could not find module `./environment.js` imported from `(require)`

It seems the new ember-auto-import@2.3.0 is unable to resolve `./environment.js` required from  `environment-ember.js`

**Comment by josemarluedke** [comment]
Hey @xomaczar! I just did a quick try to see if this was still happening in latest version of ember-auto-import v2.4 and it is. 

I believe this issue should be be opened in auto-import repo as it seems to be a regression. Versions bellow v2.3 did work correctly.

It's also worth noting that this issue happens because webpack is using cjs instead of esm. We ship cjs so we can support fastboot (nodejs).

cc/ @ef4.

**Comment by josemarluedke** [comment]
This should be fixed in v0.5.0.
